from pathlib import Path

def replace_once(path: str, old: str, new: str):
    p = Path(path)
    text = p.read_text()
    if text.count(old) != 1:
        raise SystemExit(f"{path}: expected one exact match, found {text.count(old)}")
    p.write_text(text.replace(old, new, 1))

replace_once("src/notverse/NoTVerseViews.tsx", 'import NotesExperience from "./NotesExperience";', 'import NotesSocialExperience from "./NotesSocialExperience";')
replace_once("src/notverse/NoTVerseViews.tsx", '  onSettings: () => void;\n  onOpenBook: (book: BookLike) => void;', '  onSettings: () => void;\n  onMyNotes: () => void;\n  onOpenBook: (book: BookLike) => void;')
replace_once("src/notverse/NoTVerseViews.tsx", 'if (props.active === "notes") return <NotesExperience displayName={props.displayName} avatar={props.avatar} libraryTitles={props.books.map((book) => book.title)} noteFont={props.preferences.noteFont} />;', 'if (props.active === "notes") return <NotesSocialExperience displayName={props.displayName} avatar={props.avatar} libraryTitles={props.books.map((book) => book.title)} noteFont={props.preferences.noteFont} />;')
replace_once("src/notverse/NoTVerseViews.tsx", 'if (props.active === "me") return <ProfileNotebook displayName={props.displayName} avatar={props.avatar} status={props.status} books={props.books} onSettings={props.onSettings} />;', 'if (props.active === "me") return <ProfileNotebook displayName={props.displayName} avatar={props.avatar} status={props.status} books={props.books} onSettings={props.onSettings} onMyNotes={props.onMyNotes} />;')
views=Path("src/notverse/NoTVerseViews.tsx");text=views.read_text();marker="function ProfileNotebook("
if text.count(marker)!=1: raise SystemExit("NoTVerseViews.tsx: ProfileNotebook marker mismatch")
prefix=text.split(marker,1)[0]
profile='''function ProfileNotebook({ displayName, avatar, status, books, onSettings, onMyNotes }: { displayName: string; avatar?: string; status?: string; books: BookLike[]; onSettings: () => void; onMyNotes: () => void }) {\n  const [notebooks] = usePersistentState<NotebookRecord[]>("notverse.notebooks", starterNotebooks);\n  const [notes] = usePersistentState("notverse.notes", starterNotes);\n  const mine = notes.filter((note) => note.mine || note.author === displayName);\n  const publicMine = mine.filter((note) => note.visibility === "public");\n  return <section className="notverse-view profile-notebook"><header className="profile-cover"><div className="profile-main-avatar">{avatar ? <img src={avatar} alt="" /> : displayName.slice(0, 1)}</div><div><span className="notverse-eyebrow">My Notebook</span><h1>{displayName}</h1><p>{status || "Reading, remembering and leaving Notes in the margins."}</p></div><button type="button" onClick={onSettings}>Edit profile</button></header><div className="profile-stat-row"><span><strong>{books.length}</strong> Library</span><span><strong>{notebooks.length}</strong> Notebooks</span><span><strong>{publicMine.length}</strong> Public Notes</span><span><strong>{mine.length}</strong> My Notes</span></div><section className="profile-note-summary"><div><strong>My Notes</strong><small>{mine.length} Note{mine.length === 1 ? "" : "s"} written · {publicMine.length} public</small></div><button type="button" onClick={onMyNotes} aria-label="Open My Notes">Open My Notes</button></section><section className="profile-paper"><span className="note-tape" /><h2>Created for Nancy. Shared with the world.</h2><p>Public sections show only what the reader allows. Private Notes, drafts, hidden books, history and saved files stay private.</p><div className="profile-genres"><b>Manga</b><b>Novels</b><b>Research</b><b>Comics</b></div></section><section className="notverse-section"><header><div><span>Joined Notebooks</span><h2>Your reading circles.</h2></div></header><div className="notebook-row">{notebooks.map((notebook) => <article key={notebook.id} style={{ "--notebook-accent": notebook.coverAccent } as React.CSSProperties}><span>▤</span><div><strong>{notebook.name}</strong><small>{notebook.type}</small><p>{notebook.description}</p></div></article>)}</div></section></section>;\n}\n'''
views.write_text(prefix+profile)

replace_once("src/App.tsx", '<button type="button" aria-label="Notifications">♡</button>', '<button type="button" className="activity-button" aria-label="Notifications" onClick={() => { setChatOpen(false); setActiveSection("notes"); window.location.hash = "activity"; }}>♡</button>')
replace_once("src/App.tsx", '          onSettings={() => setSettingsOpen(true)}\n          onOpenBook={openNoTVerseBook}', '          onSettings={() => setSettingsOpen(true)}\n          onMyNotes={() => { setChatOpen(false); setActiveSection("notes"); window.location.hash = "my-notes"; }}\n          onOpenBook={openNoTVerseBook}')
replace_once("src/App.tsx", '''  function closeMenus(event: MouseEvent<HTMLDivElement>) {\n    if (event.target === event.currentTarget) {\n      setSettingsOpen(false);\n    }\n  }\n\n  return (\n''', '''  function closeMenus(event: MouseEvent<HTMLDivElement>) {\n    if (event.target === event.currentTarget) {\n      setSettingsOpen(false);\n    }\n  }\n\n  useEffect(() => {\n    const routeSocialHash = () => {\n      const hash = window.location.hash;\n      if (hash === "#activity" || hash === "#my-notes" || hash.startsWith("#note=")) {\n        setChatOpen(false);\n        setActiveSection("notes");\n      }\n    };\n    routeSocialHash();\n    window.addEventListener("hashchange", routeSocialHash);\n    return () => window.removeEventListener("hashchange", routeSocialHash);\n  }, []);\n\n  return (\n''')
replace_once("src/main.tsx", 'import "./notverse/focused-inbox-viewport.css";\nimport "./notverse/ios-visual-viewport-recovery";', 'import "./notverse/focused-inbox-viewport.css";\nimport "./notverse/notes-social-completion.css";\nimport "./notverse/ios-visual-viewport-recovery";')

ios=Path("src/notverse/ios-visual-viewport-recovery.ts");text=ios.read_text();old='''function settleVisibleViewport(): void {\n  syncVisibleViewport();\n  for (const delay of [40, 100, 180, 320, 520, 800]) {\n    window.setTimeout(syncVisibleViewport, delay);\n  }\n}\n''';new='''let settleFrame = 0;\nlet settleUntil = 0;\n\nfunction settleFrameLoop(): void {\n  settleFrame = 0;\n  syncVisibleViewport();\n  if (performance.now() < settleUntil) {\n    settleFrame = window.requestAnimationFrame(settleFrameLoop);\n  }\n}\n\nfunction settleVisibleViewport(duration = 420): void {\n  syncVisibleViewport();\n  settleUntil = Math.max(settleUntil, performance.now() + duration);\n  if (!settleFrame) settleFrame = window.requestAnimationFrame(settleFrameLoop);\n}\n'''
if text.count(old)!=1: raise SystemExit("ios recovery settle block mismatch")
text=text.replace(old,new,1).replace('window.addEventListener("resize", settleVisibleViewport, { passive: true });','window.addEventListener("resize", () => settleVisibleViewport(520), { passive: true });').replace('window.addEventListener("orientationchange", settleVisibleViewport, { passive: true });','window.addEventListener("orientationchange", () => settleVisibleViewport(700), { passive: true });').replace('window.visualViewport?.addEventListener("resize", settleVisibleViewport, { passive: true });','window.visualViewport?.addEventListener("resize", () => settleVisibleViewport(520), { passive: true });').replace('window.visualViewport?.addEventListener("scroll", settleVisibleViewport, { passive: true });','window.visualViewport?.addEventListener("scroll", () => settleVisibleViewport(520), { passive: true });')
text=text.replace('    settleVisibleViewport();\n  }\n}, true);','    settleVisibleViewport(900);\n  }\n}, true);',1).replace('    settleVisibleViewport();\n  }\n}, true);','    settleVisibleViewport(700);\n  }\n}, true);',1);ios.write_text(text)

workflow=Path(".github/workflows/mobile-notes-chat-regression.yml");text=workflow.read_text();text=text.replace('      - "scripts/prove-ios-overlay-recovery.mjs"\n','      - "scripts/prove-ios-overlay-recovery.mjs"\n      - "scripts/prove-notes-social-loop.mjs"\n',1);text=text.replace('''      - name: Prove iOS keyboard chat and Replies navigation clearance\n        run: node scripts/prove-ios-overlay-recovery.mjs\n\n      - name: Start exact generated Worker entry\n''','''      - name: Prove iOS keyboard chat and Replies navigation clearance\n        run: node scripts/prove-ios-overlay-recovery.mjs\n\n      - name: Prove Notes social loop, activity, share and real replies\n        run: node scripts/prove-notes-social-loop.mjs\n\n      - name: Start exact generated Worker entry\n''',1);text=text.replace('''            engineering-evidence/mobile-notes-chat\n            engineering-evidence/ios-overlay-recovery\n''','''            engineering-evidence/mobile-notes-chat\n            engineering-evidence/ios-overlay-recovery\n            engineering-evidence/notes-social-completion\n''',1);workflow.write_text(text)
print("Notes social completion activation patch applied.")
