from pathlib import Path
p=Path('scripts/prove-notes-social-loop.mjs')
text=p.read_text()
old='await replyInput.fill(replyText);await page.getByRole("button",{name:"Send",exact:true}).click();await page.getByText(replyText,{exact:true}).waitFor();'
new='await replyInput.fill(replyText);const replySend=page.locator(".replies-drawer>form").getByRole("button",{name:"Send",exact:true});await replySend.tap();await page.waitForFunction(()=>document.querySelector(".replies-drawer input")?.value==="");await page.getByText(replyText,{exact:true}).waitFor();'
if text.count(old)!=1: raise SystemExit(f'reply target marker mismatch: {text.count(old)}')
text=text.replace(old,new,1)
old_transition='async function keyboardTransition(browserType,browserName){const browser=await browserType.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});const page=await context.newPage();try{await prepare(page);await page.getByRole("button",{name:"Inbox",exact:true}).last().click();const input=page.locator(".inbox-layout main>form input");await input.focus();const samples=[];for(const state of[{top:0,left:0,width:390,height:353},{top:84,left:12,width:366,height:353},{top:171,left:0,width:390,height:353}]){await page.evaluate(next=>{const vv=visualViewport;if(!vv)return;Object.defineProperties(vv,{offsetTop:{configurable:true,value:next.top},offsetLeft:{configurable:true,value:next.left},width:{configurable:true,value:next.width},height:{configurable:true,value:next.height}});vv.dispatchEvent(new Event("resize"));vv.dispatchEvent(new Event("scroll"));},state);await page.waitForTimeout(90);samples.push(await page.locator(".inbox-layout main>form").evaluate(node=>{const b=node.getBoundingClientRect();return{left:b.left,width:b.width,bottom:b.bottom};}));}await page.waitForTimeout(750);const finalBox=await page.locator(".inbox-layout main>form").evaluate(node=>{const b=node.getBoundingClientRect();return{left:b.left,width:b.width,bottom:b.bottom};});assert(samples.every(box=>Math.abs(box.left)<=1&&Math.abs(box.width-390)<=1),`${browserName}: Inbox moved sideways during focus transition`);const minBottom=Math.min(...samples.map(box=>box.bottom));assert(minBottom>=finalBox.bottom-12,`${browserName}: Inbox composer undershot final keyboard edge (${minBottom} < ${finalBox.bottom})`);await page.screenshot({path:`${out}/${browserName}-390-inbox-focus-transition.png`,fullPage:false});report.cases.push({browserName,keyboardTransition:true,samples,finalBox});}finally{await context.close();await browser.close();}}'
new_transition='async function keyboardTransition(browserType,browserName){const browser=await browserType.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});const page=await context.newPage();try{await prepare(page);await page.getByRole("button",{name:"Inbox",exact:true}).last().click();const input=page.locator(".inbox-layout main>form input");await input.focus();const targetBottom=353;const samples=[];for(const state of[{top:0,left:0,width:390,height:targetBottom},{top:84,left:12,width:366,height:targetBottom-84},{top:171,left:0,width:390,height:targetBottom-171}]){await page.evaluate(next=>{const vv=visualViewport;if(!vv)return;Object.defineProperties(vv,{offsetTop:{configurable:true,value:next.top},offsetLeft:{configurable:true,value:next.left},width:{configurable:true,value:next.width},height:{configurable:true,value:next.height}});vv.dispatchEvent(new Event("resize"));vv.dispatchEvent(new Event("scroll"));},state);await page.waitForTimeout(90);samples.push(await page.locator(".inbox-layout main>form").evaluate(node=>{const b=node.getBoundingClientRect();return{left:b.left,width:b.width,bottom:b.bottom};}));}await page.waitForTimeout(750);const finalBox=await page.locator(".inbox-layout main>form").evaluate(node=>{const b=node.getBoundingClientRect();return{left:b.left,width:b.width,bottom:b.bottom};});assert(samples.every(box=>Math.abs(box.left)<=1&&Math.abs(box.width-390)<=1),`${browserName}: Inbox moved sideways during focus transition`);assert(samples.every(box=>Math.abs(box.bottom-targetBottom)<=8),`${browserName}: Inbox composer moved away from keyboard edge during transition ${JSON.stringify(samples)}`);assert(Math.abs(finalBox.left)<=1&&Math.abs(finalBox.width-390)<=1,`${browserName}: Inbox final horizontal geometry moved ${JSON.stringify(finalBox)}`);assert(Math.abs(finalBox.bottom-targetBottom)<=8,`${browserName}: Inbox final composer left keyboard edge ${finalBox.bottom} vs ${targetBottom}`);await page.screenshot({path:`${out}/${browserName}-390-inbox-focus-transition.png`,fullPage:false});report.cases.push({browserName,keyboardTransition:true,targetBottom,samples,finalBox});}finally{await context.close();await browser.close();}}'
if text.count(old_transition)!=1: raise SystemExit(f'keyboard transition marker mismatch: {text.count(old_transition)}')
text=text.replace(old_transition,new_transition,1)
p.write_text(text)
print('Scoped social reply proof to a real mobile tap and fixed transition proof to one keyboard edge.')
